name: "Request new package"
description: "Request to add a new package to the repository"
title: "[newpkg] package-name"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for requesting a new package. Please fill in the form below.
  - type: checkboxes
    id: precheck
    attributes:
      label: "Pre-submission checklist"
      description: "Please confirm the following before submitting"
      options:
        - label: "The package is not available in the official Arch repositories"
          required: true
        - label: "The package has not already been requested"
          required: true
  - type: input
    id: upstream
    attributes:
      label: "Upstream URL"
      description: |
        Link to the upstream project of the software, such as its website
        or source repository.
      placeholder: "https://example.org/software"
    validations:
      required: true
  - type: textarea
    id: purpose
    attributes:
      label: "Purpose"
      description: |
        What does the package do? Who is it for? What are its benefits over existing alternatives?
    validations:
      required: true
  - type: input
    id: license
    attributes:
      label: "License"
      description: |
        The submitted software should be free (as in freedom) software, or at least open source software.
        Only the name is needed for standard licenses, e.g. GPL-3.0-or-later. Include a link for non-standard licenses.
      placeholder: "GPL-3.0-or-later"
    validations:
      required: true
